### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [KRILLE123/esx-kr-bag-inventory#1]
So i have been getting this error. Not sure how to fix it. I saw the fivem thread that it could be due to multi-character  so i then disable it but i get the same error.  Could you help me with this error please?
I'm still trying to see if i can find a fix myself in the meantime. Just thought i'd ask you just in case you know how to fix. Thanks!

`Error running call reference function for resource esx-kr-bag-inventory: citizen:/scripting/lua/scheduler.lua:403: server/main.lua:28: attempt to index a nil value
stack traceback:
        server/main.lua:28: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:626: in field '?'
        server/functions.lua:33: in field 'TriggerServerCallback'
        server/common.lua:63: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>`

**Comment by KRILLE123** [comment]
Hey try download the latest version.

**Comment by XxFri3ndlyxX** [comment]
Hey thanks for the update. This seem to have done the trick. I really really love your script. This is very cool.
